/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingModuleRouteImport } from './routes/training-module'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiModulesSyncRouteImport } from './routes/api/modules-sync'

const TrainingModuleRoute = TrainingModuleRouteImport.update({
  id: '/training-module',
  path: '/training-module',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModulesSyncRoute = ApiModulesSyncRouteImport.update({
  id: '/api/modules-sync',
  path: '/api/modules-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/certificates': typeof CertificatesRoute
  '/dashboard': typeof DashboardRoute
  '/levels': typeof LevelsRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/training': typeof TrainingRoute
  '/training-module': typeof TrainingModuleRoute
  '/api/modules-sync': typeof ApiModulesSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/certificates': typeof CertificatesRoute
  '/dashboard': typeof DashboardRoute
  '/levels': typeof LevelsRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/training': typeof TrainingRoute
  '/training-module': typeof TrainingModuleRoute
  '/api/modules-sync': typeof ApiModulesSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/certificates': typeof CertificatesRoute
  '/dashboard': typeof DashboardRoute
  '/levels': typeof LevelsRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/training': typeof TrainingRoute
  '/training-module': typeof TrainingModuleRoute
  '/api/modules-sync': typeof ApiModulesSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/certificates'
    | '/dashboard'
    | '/levels'
    | '/login'
    | '/modules'
    | '/progress'
    | '/reports'
    | '/training'
    | '/training-module'
    | '/api/modules-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/certificates'
    | '/dashboard'
    | '/levels'
    | '/login'
    | '/modules'
    | '/progress'
    | '/reports'
    | '/training'
    | '/training-module'
    | '/api/modules-sync'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/certificates'
    | '/dashboard'
    | '/levels'
    | '/login'
    | '/modules'
    | '/progress'
    | '/reports'
    | '/training'
    | '/training-module'
    | '/api/modules-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CertificatesRoute: typeof CertificatesRoute
  DashboardRoute: typeof DashboardRoute
  LevelsRoute: typeof LevelsRoute
  LoginRoute: typeof LoginRoute
  ModulesRoute: typeof ModulesRoute
  ProgressRoute: typeof ProgressRoute
  ReportsRoute: typeof ReportsRoute
  TrainingRoute: typeof TrainingRoute
  TrainingModuleRoute: typeof TrainingModuleRoute
  ApiModulesSyncRoute: typeof ApiModulesSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training-module': {
      id: '/training-module'
      path: '/training-module'
      fullPath: '/training-module'
      preLoaderRoute: typeof TrainingModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modules-sync': {
      id: '/api/modules-sync'
      path: '/api/modules-sync'
      fullPath: '/api/modules-sync'
      preLoaderRoute: typeof ApiModulesSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CertificatesRoute: CertificatesRoute,
  DashboardRoute: DashboardRoute,
  LevelsRoute: LevelsRoute,
  LoginRoute: LoginRoute,
  ModulesRoute: ModulesRoute,
  ProgressRoute: ProgressRoute,
  ReportsRoute: ReportsRoute,
  TrainingRoute: TrainingRoute,
  TrainingModuleRoute: TrainingModuleRoute,
  ApiModulesSyncRoute: ApiModulesSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
